<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tw.DependencyInjection.Autofac</RootNamespace>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Autofac.Extras.DynamicProxy" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tw.DependencyInjection\Tw.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tw.DependencyInjection.Tests" />
  </ItemGroup>

</Project>
