<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\EventBus\Tw.EventBus.Cap\Tw.EventBus.Cap.csproj" />
    <ProjectReference Include="..\..\..\src\EventBus\Tw.EventBus\Tw.EventBus.csproj" />
    <ProjectReference Include="..\..\..\src\Data\Tw.Data\Tw.Data.csproj" />
  </ItemGroup>
</Project>
